spring:
  profiles:
    active: dev

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    driver-class-name: org.postgresql.Driver

app:
  sql:
    findAllByNickname:
      path: file:sql-request.sql
  websocket:
    endpoints: '/status'
    allowed-origins: '*'

logging:
  level:
    root: INFO
    vnavesnoj.spring.database.pool: INFO
    org.springframework.jdbc.core: INFO